@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDM3NTM5NjksInNjb3BlIjpbInVzZXIiXSwidWlkIjoxfQ.jQnSGfnoTUbYqyObhMWghW-e2tB4Zhlb80TSLwxC9aI
@baseUrl = http://0.0.0.0:9090

GET {{baseUrl}}/status